version: "3"

services:
  #builder:
  #  container_name: go-builder
  #  image: rabbotio/go-builder
  hello-go:
    container_name: hello-go
    env_file: .env
    environment:
      - PORT=${PORT:-8080}
    image: rabbotio/hello-go
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./.env:/app/.env
      - ./:/app
    # working_dir: /app
    # command: glide update && fresh -c runner.conf main.go
